### ISSUE TITLE
ek office me O bada and ek me chhota

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#100]
![Screenshot 2020-06-12 at 7 55 53 AM](https://user-images.githubusercontent.com/41849556/84458262-3d285200-ac82-11ea-9ab5-8b1afb2f705c.png)

**Comment by Avinash-ecb** [comment]
Issue is fixed now and discussed with vinod sir

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/84559325-42a39c00-ad57-11ea-818c-b30ea929243d.png)
