### ISSUE TITLE
language suggestion nahi aa raha

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#101]
![Screenshot 2020-06-12 at 7 57 34 AM](https://user-images.githubusercontent.com/41849556/84458352-782a8580-ac82-11ea-92a1-5bf1ed81bee8.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/85096549-349bc280-b212-11ea-8a6b-8dbd0644751b.png)
