### ISSUE TITLE
image nahi hai toh itna design kharab kaise

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#102]
![Screenshot 2020-06-12 at 7 59 09 AM](https://user-images.githubusercontent.com/41849556/84458476-b627a980-ac82-11ea-952b-1519d2a43da0.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/84618154-f2f7d880-aeee-11ea-9d6d-344cca1da6a3.png)
