### ISSUE TITLE
Load nai ho raha he

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/Fammeo#104]
https://www.fammeo.in/p/member/vinpahilwani/

**Comment by Avinash-ecb** [comment]
@mitulpanch  try this url
https://www.fammeo.in/p/member/vinpahilwani

**Comment by mitulpanch** [comment]
ha url pata he, but uper wali url incorrect he to redirect kardo

**Comment by Avinash-ecb** [comment]
Ok sir I will change this

**Comment by Avinash-ecb** [comment]
now this issue is fiexed

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/84731694-47668b00-afb7-11ea-9b9d-b114b4fd0479.png)
