### ISSUE TITLE
Image Issue

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/Fammeo#105]
![Annotation 2020-06-11 090619](https://user-images.githubusercontent.com/5259926/84530906-53292780-ad01-11ea-967f-d380dd96f153.jpg)

**Comment by Avinash-ecb** [comment]
this issues is solved now
![image](https://user-images.githubusercontent.com/46588125/84568357-8967b500-ad9c-11ea-8f00-fa2101ffda36.png)
