### ISSUE TITLE
Fammeo Title Menu Background Required

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/Fammeo#107]
![Annotation 2020-06-13 092705](https://user-images.githubusercontent.com/5259926/84559418-12103200-ad58-11ea-9b58-5e26932341d8.jpg)

This looks little dull

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/84618026-7107af80-aeee-11ea-8a13-f8c8445c0111.png)
