### ISSUE TITLE
Ui issue on mydashboard

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#108]
![image](https://user-images.githubusercontent.com/58812881/84559422-189ea980-ad58-11ea-9a27-5a0e75158a5b.png)

**Comment by Avinash-ecb** [comment]
this issues is solved now organization image will display like this
![image](https://user-images.githubusercontent.com/46588125/84563398-ee111880-ad78-11ea-850c-9d60174cc3d8.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/84617943-37cf3f80-aeee-11ea-8d95-33fdac797e75.png)
