### ISSUE TITLE
create organisation - title bar k upar aa raha hai slide karne pe

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#114]
![Screenshot 2020-06-13 at 8 16 21 PM](https://user-images.githubusercontent.com/41849556/84571779-36e5c300-adb3-11ea-862d-3357bee4d565.png)

**Comment by Avinash-ecb** [comment]
now this issue is fixed
![image](https://user-images.githubusercontent.com/46588125/84619320-59cac100-aef2-11ea-9c64-6c2597e5ccae.png)

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/84731331-2b161e80-afb6-11ea-84f2-8d9ddcad3323.png)
