### ISSUE TITLE
Language display two times

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/Fammeo#119]
Language display two times 
![image](https://user-images.githubusercontent.com/46588125/84626763-55f36a80-af03-11ea-8ecd-c91dc023bd37.png)

**Comment by mitulpanch** [comment]
Kya he ye Error?

**Comment by Avinash-ecb** [comment]
Database me name ki jagah description hai and description ki jagah name hai apko ekbar dikhaya tha
