### ISSUE TITLE
Don't show about section

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/Fammeo#124]
When visiting other user profile and his profile has no title and discription then don' display about section by @dharmendraecb 
![image](https://user-images.githubusercontent.com/46588125/84640180-facb7300-af16-11ea-876a-b90d00c2b4ac.png)

**Comment by Avinash-ecb** [comment]
this issue is now fixed
![image](https://user-images.githubusercontent.com/46588125/84653016-391e5d80-af2a-11ea-9b05-77c6b9e46485.png)

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/84731162-a75c3200-afb5-11ea-93d9-df55419702ef.png)
