### ISSUE TITLE
When Click on pending button that time not cancel request 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#128]
![2020-06-15_1651](https://user-images.githubusercontent.com/58812881/84652037-8f8a9c80-af28-11ea-9edb-66e20d8ff643.png)

**Comment by jayshah6777** [comment]
pending ka name change withdraw karna he

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/86583215-7feafa80-bfa0-11ea-9999-44f0cfffc5a6.png)
name changed

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/86725072-f93d2880-c046-11ea-8fa1-7ae304f0c076.png)
