### ISSUE TITLE
language issue

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#130]
1. language ka ek hi word aana chahiye . marathi do do aa raha hai
2. punjabi toh option aa hi nahi raha
![Screenshot 2020-06-16 at 6 47 34 AM](https://user-images.githubusercontent.com/41849556/84721121-84be1f00-af9d-11ea-83bb-979c84e42bdb.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/84730804-e0e06d80-afb4-11ea-9857-d0d605e67b5f.png)
