### ISSUE TITLE
mere friends ka number and email id toh dikhna chahiye 

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#131]
mere friends ka number and email id toh dikhna chahiye. sabhi jagah nahi toh is connections mein friends k andar toh ho hi sakta hai
![Screenshot 2020-06-16 at 6 50 00 AM](https://user-images.githubusercontent.com/41849556/84721266-e8484c80-af9d-11ea-9d4c-697537489f82.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/84730621-4e3fce80-afb4-11ea-83f0-98dfe0dbebe5.png)
