### ISSUE TITLE
put a popup msg when user put cursor on button

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#133]
![image](https://user-images.githubusercontent.com/58812881/84732602-bd6bf180-afb9-11ea-8b90-848d20bfccdc.png)

1) when user used dark mode  show light button and when user used light mode show dark button
2) show popup msg on full scree button
3) show popup msg on notification button
4) show popup msg on profile button

**Comment by vinpahilwani** [comment]
ok i agree on this

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/84857459-be1e8980-b086-11ea-9314-2f07cb1f6a1c.png)
