### ISSUE TITLE
line change

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/Fammeo#135]
"Other users can see who I am following and who follows me" sir this line is sound too awkward... 
instead of this.. we can simply write "Other users can see my following and followers"

![image](https://user-images.githubusercontent.com/66782635/84743044-ffebf900-afce-11ea-8641-0faaca1eacda.png)

**Comment by vinpahilwani** [comment]
right i approve this

**Comment by Avinash-ecb** [comment]
this issue is fixed now
![image](https://user-images.githubusercontent.com/46588125/84756932-17cc7880-afe1-11ea-8b8a-df2be3ec5f76.png)

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/84854802-2e75dc80-b080-11ea-8eb3-ae838a1b1cec.png)
