### ISSUE TITLE
 about section is not showing in my profile

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/Fammeo#137]
![image](https://user-images.githubusercontent.com/66782635/84889484-8e877580-b0b6-11ea-86e5-211285c1c86e.png)

about click is not working..... do not show anything on this click......

**Comment by Avinash-ecb** [comment]
this issue is fixed 
![image](https://user-images.githubusercontent.com/46588125/84895963-c5628900-b0c0-11ea-9d98-c71e24045043.png)

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/84977082-1e750000-b147-11ea-8f7d-67475f31aaca.png)
