### ISSUE TITLE
organisation description error

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/Fammeo#141]
![image](https://user-images.githubusercontent.com/66782635/85100125-f22bb300-b21c-11ea-8e01-afc6506a0dd4.png)

there is no special character write in description.... still showing an error......

**Comment by Avinash-ecb** [comment]
This issue is fixed now

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/85250076-2698ac80-b473-11ea-8681-590b759c62fb.png)
