### ISSUE TITLE
Add tag in member profile 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/Fammeo#143]
add, edit ,delete tag

**Comment by Avinash-ecb** [comment]
@mitulpanch  /user/getuser is api me scope me tag pass karne par tag vala data chahiye

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/85252307-1a175280-b479-11ea-9235-0ae6f754c522.png)


tags are not remove/delete by user

**Comment by Avinash-ecb** [comment]
now you can delete tags
