### ISSUE TITLE
Whenever goto the user's experience page then get a notification 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#144]
![image](https://user-images.githubusercontent.com/58812881/85125785-dee30c80-b249-11ea-8a85-474788ece421.png)

1) when user's experience is blank that time shouldn't show experience Button

**Comment by harshitaexpcon** [comment]
also improve "You donot have enough Privilege", add space between "do not"

**Comment by Avinash-ecb** [comment]
@mitulpanch  when watching other user experience with login my id  then in /user/getindustries api there is checking haveperimssion in that session userid and userid we have pass will not match get getting condition false so showing error you donot have enough privilege 
same thing is happening in /user/getsoftwares api

and You donot have enough Privilege this message is coming from api so change this also

**Comment by Avinash-ecb** [comment]
issue fixed
