### ISSUE TITLE
Design Change- Conversation

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/Fammeo#146]
![Annotation 2020-06-19 183301-2](https://user-images.githubusercontent.com/5259926/85135250-74d36300-b25b-11ea-8aa0-9728b492f5c4.jpg)
![Annotation 2020-06-19 183301](https://user-images.githubusercontent.com/5259926/85135254-769d2680-b25b-11ea-9474-9a90877014bd.jpg)

**Comment by mitulpanch** [comment]
75 % Max Width
PAdding kam karo

Left Align Text
time ko Transparent kardo - 50%

Remove Background Color - Make White Background for all message

**Comment by mitulpanch** [comment]
Reply ko Chat Jesa kardo
Reverse Sorting Chahiye ab

Make Box - 8/4 size

**Comment by jayshah6777** [comment]
![Uploading image.png…]()
