### ISSUE TITLE
Extra Padding

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/Fammeo#148]
![Annotation 2020-06-19 183301-2](https://user-images.githubusercontent.com/5259926/85138052-c2ea6580-b25f-11ea-91b7-0ed6f97ec0df.jpg)

**Comment by Avinash-ecb** [comment]
this issue is fixed
![image](https://user-images.githubusercontent.com/46588125/85256848-79c62b80-b482-11ea-856f-117d6de2838c.png)
