### ISSUE TITLE
Padding Error

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/Fammeo#151]
![Annotation 2020-06-19 183301-2](https://user-images.githubusercontent.com/5259926/85138309-2d030a80-b260-11ea-894d-1dbfa4898674.jpg)

**Comment by Avinash-ecb** [comment]
this issue is fixed now
![image](https://user-images.githubusercontent.com/46588125/85253985-e50cff00-b47c-11ea-8176-d1df15e3ad9b.png)
