### ISSUE TITLE
Background image problem in member profile

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/Fammeo#152]
After changing background image and refresh image size change to small
![image](https://user-images.githubusercontent.com/46588125/85198035-0053ff00-b303-11ea-9b8b-3cd37e51fb0d.png)

**Comment by Avinash-ecb** [comment]
Image resolution 850x315 aa raha hai api se

**Comment by mitulpanch** [comment]
Dont set Image from javascript,
Let Server first save image according to fammeo. then show image,

resolution will be 850*315

**Comment by Avinash-ecb** [comment]
This issue is fixed
