### ISSUE TITLE
add whatsapp number in social links

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/Fammeo#154]
Add whatsapp number in social linkes

**Comment by Avinash-ecb** [comment]
this issue is fixed now
![image](https://user-images.githubusercontent.com/46588125/85279232-b5252200-b4a3-11ea-8180-6a0d33efd000.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/85382987-1c52dd00-b55d-11ea-83b1-13f1cd46e42a.png)

**Comment by Avinash-ecb** [comment]
now add 10 digit mobile number starting from 6 or greater than 6
![image](https://user-images.githubusercontent.com/46588125/85397661-92f9d580-b571-11ea-92d9-f0b858eb83df.png)

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/85500917-021f0a80-b602-11ea-83e7-cb0fc04d2058.png)
