### ISSUE TITLE
When Tag's section is blank don't show on user profile 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#156]
![image](https://user-images.githubusercontent.com/58812881/85366241-90cd5200-b544-11ea-991c-e26c7b94daaa.png)

**Comment by Avinash-ecb** [comment]
this issue is solved now

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/85500171-a4d68980-b600-11ea-8de4-bb920b50279a.png)
