### ISSUE TITLE
Profile me profile video lena ka rakho 

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#16]
![Screenshot 2020-05-23 at 6 27 04 AM](https://user-images.githubusercontent.com/41849556/82718165-6d518600-9cbe-11ea-89e4-4d0e2b682f0b.png)

**Comment by mitulpanch** [comment]
Adding new blob setting for this

**Comment by mitulpanch** [comment]
AboutVideo Blob Setting now available on save basicdata api for user/company
