### ISSUE TITLE
Inustry experience in company experience

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/Fammeo#160]
Add, edit and delete industry experience in company profile experience

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/85914247-4a843580-b859-11ea-83e5-0c7c64419b5f.png)

this issue is fixed

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/85914376-b3b87880-b85a-11ea-812a-ceb9263bc1bd.png)
