### ISSUE TITLE
change instruction in organisation profile

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/Fammeo#162]
![image](https://user-images.githubusercontent.com/66782635/85819239-b484d800-b790-11ea-806a-46978b4a765c.png)

username end with char. also....

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/85819428-42f95980-b791-11ea-92a5-f6acd9e28701.png)

**Comment by mitulpanch** [comment]
Only First Letter Requirement as Character

**Comment by mitulpanch** [comment]
@Avinash-ecb Please change text according to this

**Comment by Avinash-ecb** [comment]
@mitulpanch  when entering last letter full stop (.) there is api error 
![image](https://user-images.githubusercontent.com/46588125/85845756-61c41400-b7c2-11ea-80f2-6862afa32e27.png)

**Comment by Avinash-ecb** [comment]
changed instruction
![image](https://user-images.githubusercontent.com/46588125/85847946-f419e700-b7c5-11ea-8595-a2126e1f3768.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/86463870-f642ef00-bd4b-11ea-923d-75e922a26b47.png)
