### ISSUE TITLE
Footer issue 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/Fammeo#165]
full page is not displayed in some pages
![image](https://user-images.githubusercontent.com/46588125/85914690-1101f900-b85e-11ea-8df0-9434ac7284e3.png)

**Comment by Avinash-ecb** [comment]
This issue is fixed now
![image](https://user-images.githubusercontent.com/46588125/85917834-3bae7a80-b87b-11ea-89b2-d9be5d873f3e.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/85972222-fad67300-b9ec-11ea-9773-b93b6b35e2f7.png)
