### ISSUE TITLE
design change of background and profile picture

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/Fammeo#166]
![image](https://user-images.githubusercontent.com/58812881/85915579-51657500-b866-11ea-88b2-55d62ee521a7.png)

1) chnage design of background and profile picture.
2) if user do not put any background picture than there is a default background picture.

**Comment by Avinash-ecb** [comment]
Set default background image

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/87637861-7c096600-c760-11ea-95d7-d81709fcea4c.png)
