### ISSUE TITLE
connection page and notification error

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/Fammeo#167]
![image](https://user-images.githubusercontent.com/66782635/85915086-2d079980-b862-11ea-953e-96fe2a61469e.png)

when i click on connection request...

![image](https://user-images.githubusercontent.com/66782635/85915090-3c86e280-b862-11ea-91bf-41612d3ce8e3.png)

the connection page did not open....

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/108582795-6fcf3200-735b-11eb-8b5d-e3a71690a940.png)
![image](https://user-images.githubusercontent.com/46588125/108582804-7c538a80-735b-11eb-8e08-ebab50c80704.png)
This issue still exist on click of connection request below url open in new tab
https://www.fammeo.in/p/member/www.fammeo.in/p/
