### ISSUE TITLE
Industry in company profile

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/Fammeo#168]
industry in about menu in company profile
add, edit and delete

**Comment by Avinash-ecb** [comment]
This issue is fixed now
![image](https://user-images.githubusercontent.com/46588125/85977860-0af54f00-b9fb-11ea-9239-0e888e53849d.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/85983120-93c4b880-ba04-11ea-9981-14ec5bddbbde.png)
