### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/Fammeo#172]
![image](https://user-images.githubusercontent.com/66782635/85972110-a501cb00-b9ec-11ea-95bd-c70c2cd475de.png)

Design issue :  remove null space from follower page or design like following page

![image](https://user-images.githubusercontent.com/66782635/85972127-ac28d900-b9ec-11ea-8d22-9d7a62dfd25c.png)

**Comment by dharmendraecb** [comment]
hawa  google add  ka section he
