### ISSUE TITLE
Group name should be Accept both Capital & small char.

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#173]
![image](https://user-images.githubusercontent.com/58812881/85983515-439a2600-ba05-11ea-9b9a-887e0a6a77dd.png)

1) if user enter capital char in group name. it by default converted into small char
2) but it should be Accept Capital and small char name

**Comment by dharmendraecb** [comment]
default group name, user name, company name first letter capital.

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/86435765-69ce0780-bd1e-11ea-81ff-dcc66a4fbefa.png)
