### ISSUE TITLE
when user after long time refresh page show relogin option 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#181]
![image](https://user-images.githubusercontent.com/58812881/86108487-d52a9600-bae0-11ea-8beb-b5438fa2843a.png)

1) home page and login page button not working 
2) design issue 
3)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/86506925-a3bc0e00-bdf1-11ea-8ccd-792733ab8b86.png)
1 button issue 
2 design issue 
solved
if you wait for long time session is closed so it again ask for login
