### ISSUE TITLE
Please correct Unfriend spelling 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#184]
https://www.fammeo.in/p/member/jayshah/connections

![image](https://user-images.githubusercontent.com/58812881/86209391-26459300-bb90-11ea-8738-f98b860d58bc.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/86234870-33c14400-bbb5-11ea-9b9e-d1bbaee2a317.png)


this issue is solved

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/86321404-8d2d7f80-bc56-11ea-8182-28426b3a4721.png)
