### ISSUE TITLE
Company profile photo & backgroud photo don't working 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#185]
![image](https://user-images.githubusercontent.com/58812881/86209946-432e9600-bb91-11ea-8057-e7e726dd3545.png)

**Comment by Avinash-ecb** [comment]
@mitulpanch  
Member profile image change karne par
image is raha se aa rahi hai

GetRelativeImage(message.obj.I, message.obj.FN, message.obj.LN, false, 256);

https://storage.googleapis.com/fammeo-usercontent/glogo/0/up/thumb_64_up_UWG9kQiQCUmgQHi_aZTcRA.jpg?v=637291990865590427

**Comment by Avinash-ecb** [comment]
@mitulpanch  
Member Background image change karne par image  https://storage.googleapis.com/fammeo-usercontent/glogo/0/ubgp/upbg_cq3dpqz69ky00g7h0vxzyg.jpg?v=637294378526318231 ye milti hai

![image](https://user-images.githubusercontent.com/46588125/86505805-cd236c80-bde6-11ea-91f8-f29f29b3e512.png)

**Comment by mitulpanch** [comment]
Need to Change Image once

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/86556420-ed7f3280-bf70-11ea-8898-12b81c90bb04.png)
