### ISSUE TITLE
Instagram link issue in company about

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#186]
![2020-07-01_1506](https://user-images.githubusercontent.com/58812881/86228887-96faa880-bbac-11ea-974f-5f59fae09b5b.png)

1) when Instagram link provided but Instagram link text box showing blank

**Comment by Avinash-ecb** [comment]
this issue is solved

![image](https://user-images.githubusercontent.com/46588125/86236963-8819f300-bbb8-11ea-9b24-3f1fd5160aef.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/86321301-5c4d4a80-bc56-11ea-9c9e-37e4a660c3a7.png)
