### ISSUE TITLE
Group profile picture issue 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#187]
![image](https://user-images.githubusercontent.com/58812881/86230460-b561a380-bbae-11ea-86cc-8112fc450b43.png)

1) User create new group and don't put profile picture that time show black color image 
2) i think we should provide logo like user logo ( without profile picture user logo show in conversation )

**Comment by mitulpanch** [comment]
How to Repeat this?
Provide steps
@jayshah6777
