### ISSUE TITLE
Change spelling in company receive request page 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#189]
![2020-07-02_1156](https://user-images.githubusercontent.com/58812881/86323829-28c0ef00-bc5b-11ea-823c-93ba6c5300b7.png)

https://www.fammeo.in/p/org/pranavsales/received

**Comment by Avinash-ecb** [comment]
changed spelling

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/86433933-a4817100-bd19-11ea-8883-81d8708636d0.png)
