### ISSUE TITLE
Team & receive request issue 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#192]
![image](https://user-images.githubusercontent.com/58812881/86436145-4eafc780-bd1f-11ea-9fe0-cb58933ee464.png)

https://www.fammeo.in/p/org/pranavsales/team

When Remove team member from team 

again show accept and reject option in Received request 

https://www.fammeo.in/p/org/pranavsales/received

![image](https://user-images.githubusercontent.com/58812881/86436314-a51d0600-bd1f-11ea-83d7-c6f198abf306.png)

**Comment by Avinash-ecb** [comment]
@mitulpanch  please check this issue

**Comment by Avinash-ecb** [comment]
Issue fixed

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/88770117-f1325d80-d19a-11ea-9df5-5b501c1d08f9.png)

**Comment by Avinash-ecb** [comment]
1 where user add experience in abc organisation
2 this user shows in received request section in abc organisation 
3 after accepting request user shows in in team list 
**4 after remove from team list user again shows in  received request section in abc organisation**
