### ISSUE TITLE
When user on receive request page that time Team tab should show in black color 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#193]
![image](https://user-images.githubusercontent.com/58812881/86436689-63d92600-bd20-11ea-9e16-90097a5e31bd.png)

**Comment by Avinash-ecb** [comment]
this issue is solved
![image](https://user-images.githubusercontent.com/46588125/86560327-a8143280-bf7b-11ea-94ea-96940f4d6b86.png)

**Comment by jayshah6777** [comment]
![Uploading image.png…]()
