### ISSUE TITLE
Ui issue in company career page 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#194]
https://www.fammeo.in/p/org/pranavsales/career

![image](https://user-images.githubusercontent.com/58812881/86436981-1e692880-bd21-11ea-8d29-10e7196d2308.png)

this issue show in light theme

**Comment by Avinash-ecb** [comment]
this issue is fixed now

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/86561667-d0e9f700-bf7e-11ea-85bc-85efd89fb2cf.png)
