### ISSUE TITLE
User already in team member but show in receive request tab

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#197]
![image](https://user-images.githubusercontent.com/58812881/86459742-e7a50980-bd44-11ea-8d82-1fb91b8cb2a4.png)

![image](https://user-images.githubusercontent.com/58812881/86459807-f5f32580-bd44-11ea-98a6-528a9c35bd3f.png)

**Comment by Avinash-ecb** [comment]
after discussion with @mitulpanch 
sir koi company kisi user ko team me add kar rahi hai and vahi user usi company me apna experience dal raha hai to user ne jo experience dala hai o company ke receved request me and company ne jo member add kiya hai o team me dikhega  o member same ho phir bhi
ye possible hai na sir?

this is possible
