### ISSUE TITLE
user get URL(link) in message. it should be open in new tab 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#202]
![image](https://user-images.githubusercontent.com/58812881/86584181-25eb3480-bfa2-11ea-80f5-fd610b2669a2.png)

**Comment by dharmendraecb** [comment]
![Screenshot_2020-07-15 Fammeo - Messages](https://user-images.githubusercontent.com/46588108/87520167-35eccd80-c6a0-11ea-8d85-909e479d8e01.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/87629582-eb775980-c750-11ea-9df1-307c3c94a5e5.png)
