### ISSUE TITLE
User can't claimed any company (organization)

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#214]
![image](https://user-images.githubusercontent.com/58812881/86880710-b5135c00-c10a-11ea-81ec-6a11387884e5.png)

**Comment by Avinash-ecb** [comment]
@mitulpanch sir there is api error please check this

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/87216648-4844cf80-c35f-11ea-92e9-9564bb0f115a.png)
