### ISSUE TITLE
user can't change profile photo or background photo

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#215]
![image](https://user-images.githubusercontent.com/58812881/86899436-9ec7c900-c127-11ea-850f-505b8f05a207.png)

**Comment by Avinash-ecb** [comment]
@mitulpanch  here is service account issue so please fix this

**Comment by Avinash-ecb** [comment]
@mitulpanch  when change background image resolution 850x315 size it gets small size 
![image](https://user-images.githubusercontent.com/46588125/87511219-9412b400-c692-11ea-898b-558161ec2129.png)
