### ISSUE TITLE
PNG file not open in browser. when user get png file in message 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#217]
![image](https://user-images.githubusercontent.com/58812881/86914889-ad6daa80-c13e-11ea-9ab7-4c7077f2c5e9.png)

**Comment by dharmendraecb** [comment]
![2020-07-08](https://user-images.githubusercontent.com/46588108/87000000-9926bd80-c1d1-11ea-8d79-8bfe3888014c.png)

**Comment by dharmendraecb** [comment]
download file error

**Comment by Harsheasy** [comment]
All image is display in brower and also pdf and world file check done
