### ISSUE TITLE
company notification

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/Fammeo#220]
![image](https://user-images.githubusercontent.com/66782635/87008557-9338d880-c1e1-11ea-8ff5-5033202edc5d.png)

company  team request notification is not showing in the notification list

**Comment by vinpahilwani** [comment]
agar staff 
1. already fammeo pe hai toh notification trigger hona chahiye
2. nahi hai fammeo pe toh usko email jayega

**Comment by mitulpanch** [comment]
Notification done
