### ISSUE TITLE
issues in add team member page

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#222]
Step 1:  add team member --> search bar -->  add “space” in the search box 

![image](https://user-images.githubusercontent.com/58812881/87030923-ee79c380-c1ff-11ea-8f9e-a144b3378f37.png)

Step 2: show this type of display --> click on create button

![image](https://user-images.githubusercontent.com/58812881/87031015-0cdfbf00-c200-11ea-8d80-41b5719c7e75.png)

Get this display after 2 steps.

![image](https://user-images.githubusercontent.com/58812881/87031059-1c5f0800-c200-11ea-8e83-a57bd1a82054.png)

Final output:  company created successfully.

its is not appropriate output and 
1) null or space value should not be contained in the search box

https://www.fammeo.in/p/user/search?cid=MXJPNDdhdGNFMDJZOEd1R0h4MHY3Zw==

**Comment by Avinash-ecb** [comment]
this issue is fixed
![image](https://user-images.githubusercontent.com/46588125/87037123-61d40300-c209-11ea-974e-95340d12b77f.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/87116053-8627f200-c292-11ea-9429-e8fd985f4169.png)
