### ISSUE TITLE
branches name is not suppose to allow null value

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#223]
![image](https://user-images.githubusercontent.com/58812881/87122270-2d605580-c2a2-11ea-89f5-8e691df06b7d.png)

![image](https://user-images.githubusercontent.com/58812881/87122159-f38f4f00-c2a1-11ea-8b44-4ba8e602abac.png)

branches name accept null Value also..... it should not allow accepting null value...

**Comment by Avinash-ecb** [comment]
this issue is fixed 
![image](https://user-images.githubusercontent.com/46588125/87132152-15dd9880-c2b3-11ea-954a-c473452dbfbc.png)
