### ISSUE TITLE
company profile Youtube link issue

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/Fammeo#224]
![image](https://user-images.githubusercontent.com/66782635/87123252-ff7c1080-c2a3-11ea-8a56-1930ec8454be.png)

in company --> about --> Youtube video link --> "add space" / "null value" 
it shows this type of display

when is click on it... it shows this type of error

![image](https://user-images.githubusercontent.com/66782635/87125520-4a982280-c2a8-11ea-9495-17bd27f90df1.png)

**Comment by Avinash-ecb** [comment]
issue is fixed
