### ISSUE TITLE
company request issue

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#225]
![image](https://user-images.githubusercontent.com/58812881/87126685-47059b00-c2aa-11ea-8e34-ad75e76598a9.png)

![image](https://user-images.githubusercontent.com/58812881/87126702-4e2ca900-c2aa-11ea-8e5e-13d285a651d1.png)

1) when user create company that time user get Experience received request 
2) it should be show only in experience

**Comment by Avinash-ecb** [comment]
@mitulpanch sir please check this error
