### ISSUE TITLE
Setting button size 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#226]
![image](https://user-images.githubusercontent.com/58812881/87142011-84c1ee00-c2c1-11ea-8f57-46c78752a5a5.png)

![image](https://user-images.githubusercontent.com/58812881/87144304-2ac32780-c2c5-11ea-9fa7-8fd7b1102e05.png)

**Comment by Avinash-ecb** [comment]
![2020-07-15](https://user-images.githubusercontent.com/46588125/87528658-700f9c80-c6ab-11ea-8944-5268216888ac.png)
issue solved

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/87629047-d77f2800-c74f-11ea-9262-1511e5d9b597.png)
