### ISSUE TITLE
When user type something in edit tags textbox then show error message 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#227]
![image](https://user-images.githubusercontent.com/58812881/87217581-69f68480-c368-11ea-99b2-3a295836e430.png)

**Comment by Avinash-ecb** [comment]
@mitulpanch  please add publictag table

**Comment by Avinash-ecb** [comment]
issue solved

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/88136016-068d1200-cc06-11ea-869f-74488a37c792.png)
