### ISSUE TITLE
Ui issue on Search education and experience please find the bellow mention link 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#230]
![image](https://user-images.githubusercontent.com/58812881/87220483-c4500f00-c381-11ea-9993-332699addf49.png)

https://www.fammeo.in/p/organization/search?edu

![image](https://user-images.githubusercontent.com/58812881/87220491-de89ed00-c381-11ea-83a9-b07892aaa6a8.png)

https://www.fammeo.in/p/organization/search?exp

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/87534946-5888e180-c6b4-11ea-9497-028021e54187.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/87628781-53c53b80-c74f-11ea-93b1-fe69b766c291.png)
.

![image](https://user-images.githubusercontent.com/58812881/87628811-5f186700-c74f-11ea-9998-9f211d991119.png)
