### ISSUE TITLE
shouldn't add multiple time same experience 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#233]
![image](https://user-images.githubusercontent.com/58812881/87272648-83c4d280-c4f4-11ea-89b6-30ea206c202a.png)

https://www.fammeo.in/p/member/jayshah_/experience

1) user add in 1 company as a present employ -> click on add organization
2) and search same company -> add as a present employ 
3) user add successfully Organization Experience 

When user add as a present employ that time shouldn't add second time as a present employ

**Comment by Avinash-ecb** [comment]
after discuss with @mitulpanch this bug go to hold
