### ISSUE TITLE
plz correct Organization spelling 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#234]
https://www.fammeo.in/p/member/jayshah_/experience

![image](https://user-images.githubusercontent.com/58812881/87273369-888a8600-c4f6-11ea-955e-15645cd2fd62.png)

![image](https://user-images.githubusercontent.com/58812881/87273414-ad7ef900-c4f6-11ea-88eb-4c9ea280ace7.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/87423531-19955600-c5f8-11ea-9a32-d97da1fd872b.png)
