### ISSUE TITLE
Title and Description me Gap rakho

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#24]
![Screenshot 2020-05-24 at 7 16 13 AM](https://user-images.githubusercontent.com/41849556/82743846-7578f680-9d8e-11ea-8bce-2941d2d68745.png)

**Comment by jayshah6777** [comment]
![2020-05-27_0853](https://user-images.githubusercontent.com/58812881/82974475-b4f64b80-9ff7-11ea-92a6-d003f2c2f651.png)
