### ISSUE TITLE
"e" capital in software Experience  

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/Fammeo#241]
user profile
![image](https://user-images.githubusercontent.com/66782635/87411290-22306100-c5e5-11ea-8215-b1cf17232cf4.png)

company profile
![image](https://user-images.githubusercontent.com/66782635/87411366-412ef300-c5e5-11ea-8698-290b05eb4bdb.png)

"e" capital in software Experience

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/87422777-dc7c9400-c5f6-11ea-8846-e3fa95b97ca9.png)
issue solved

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/87503757-a2f16a80-c682-11ea-9add-d61a553cdaae.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/87504299-d97bb500-c683-11ea-9f71-f13cebb07b2a.png)
issue solved

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/87627309-14e1b680-c74c-11ea-86fb-9447ad3a376d.png)


![image](https://user-images.githubusercontent.com/58812881/87627340-24f99600-c74c-11ea-9abe-c84b2b666ba5.png)
