### ISSUE TITLE
we can add same user only once in same company

### ISSUE THREAD

**Issue by harshitaexpcon** [Fammeo/Fammeo#243]
![image](https://user-images.githubusercontent.com/66782635/87418101-ccf94d00-c5ee-11ea-8524-747ad4a052a3.png)

![image](https://user-images.githubusercontent.com/66782635/87418061-b9e67d00-c5ee-11ea-9401-734e73df592c.png)

if user is already added in Xyz company than it will show "connected"......
we can not add again in the same company

**Comment by Avinash-ecb** [comment]
after discuss with @mitulpanch this bug go to hold

**Comment by Avinash-ecb** [comment]
After discuss with @mitulpanch sir 
user can be added multiple time
