### ISSUE TITLE
please change the word on member about and add (Add)

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#250]
1) member about me jaha pe edir likha he uski kagha pe (add) karna he 

![image](https://user-images.githubusercontent.com/58812881/87634734-7e1cf600-c75b-11ea-853a-efa815c3306f.png)

![image](https://user-images.githubusercontent.com/58812881/87634755-88d78b00-c75b-11ea-9951-16b3a3d8af2d.png)

![image](https://user-images.githubusercontent.com/58812881/87634790-93922000-c75b-11ea-8d1c-8e6cd7361b4d.png)

![image](https://user-images.githubusercontent.com/58812881/87634860-b9b7c000-c75b-11ea-892c-4af4a6e7eae6.png)

![image](https://user-images.githubusercontent.com/58812881/87634873-c2a89180-c75b-11ea-9381-434eb31b453c.png)

![image](https://user-images.githubusercontent.com/58812881/87634896-cb00cc80-c75b-11ea-95b8-b866dddd205f.png)

**Comment by Avinash-ecb** [comment]
issue fixed

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/87750612-89cef200-c819-11ea-854e-89120b829a31.png)
