### ISSUE TITLE
ui issue on education search education page 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#251]
![image](https://user-images.githubusercontent.com/58812881/87635257-5e3a0200-c75c-11ea-8576-259554d25163.png)

1) show (Add education)
2) search your university or collage or school

**Comment by Avinash-ecb** [comment]
this issue solved

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/87750483-32c91d00-c819-11ea-831d-ed9b42d4ddc3.png)
