### ISSUE TITLE
UI change on member profile page 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#252]
https://www.fammeo.in/p/member/jayshah

![image](https://user-images.githubusercontent.com/58812881/87637416-cb9b6200-c75f-11ea-8792-401af07c7252.png)

About    Education    Experience  Connections   Followers  Following   Tweets

**Comment by Avinash-ecb** [comment]
issue fixed
![image](https://user-images.githubusercontent.com/46588125/87665661-e6cc9880-c784-11ea-869d-3792698bae8e.png)
