### ISSUE TITLE
already claimed company not show for claim 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#253]
![image](https://user-images.githubusercontent.com/58812881/87639265-9cd2bb00-c762-11ea-8f5a-309646db720c.png)

https://www.fammeo.in/p/organization/search?new

1) when user search for user create company or claim that time never show already claimed company

**Comment by Avinash-ecb** [comment]
@mitulpanch  please check this issue

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/87844669-ff4fc680-c8dc-11ea-88de-a543c9387c17.png)

now claim company shows view profile button and which is not claim that company show claim button

**Comment by jayshah6777** [comment]
![Uploading image.png…]()
