### ISSUE TITLE
when user add team member that time show wrong message 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#257]
![image](https://user-images.githubusercontent.com/58812881/87663117-f21dc500-c780-11ea-8580-c1d2ac814cbf.png)

https://www.fammeo.in/p/user/connect?cid=LURiWktlNzVDa3FJWXpOaUdGeTRWQQ%3D%3D&id=Y0NqWTg0ekJhRTI2NTFHZ3VCQnJKUQ%3D%3D&n=rushang%20malusare

1) when team member add that time should be show message (Team member added successfully )

**Comment by Avinash-ecb** [comment]
issue fixed
![image](https://user-images.githubusercontent.com/46588125/87667010-46c43e80-c787-11ea-841a-30f4bff4e44d.png)
