### ISSUE TITLE
When remove team member that time show wrong message 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#258]
![image](https://user-images.githubusercontent.com/58812881/87663669-d535c180-c781-11ea-999e-f5dae0a37f60.png)

https://www.fammeo.in/p/org/pranavsales/team

1) when team member Remove that time should be show message (Team member removed successfully )

**Comment by Avinash-ecb** [comment]
issue fixed
![image](https://user-images.githubusercontent.com/46588125/87667262-ab7f9900-c787-11ea-9d67-eb027799fb2d.png)
