### ISSUE TITLE
When Accept organization request  that time show wrong message 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#259]
![image](https://user-images.githubusercontent.com/58812881/87665651-e207e480-c784-11ea-99e7-83273f377522.png)

https://www.fammeo.in/p/member/jayshah/received
1)  when accept organization Request  that time should be show message  ( Experience added successfully )

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/87667531-28ab0e00-c788-11ea-9213-1287cbc57967.png)
