### ISSUE TITLE
provide i button for Admin information 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#261]
![image](https://user-images.githubusercontent.com/58812881/87768004-1e951800-c839-11ea-9e63-4fce10bb1a3c.png)

https://www.fammeo.in/p/organization/create?n=test%20admin&t=edu

https://www.fammeo.in/p/organization/search?exp

**Comment by Avinash-ecb** [comment]
@jayshah6777 please provide i button description so I can put description in  i button

**Comment by jayshah6777** [comment]
( Trun this on if you are an admin of this organization )

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/87914008-a3786f80-ca8d-11ea-8369-0130b751f580.png)
Issue fixed

**Comment by jayshah6777** [comment]
![Uploading image.png…]()
