### ISSUE TITLE
Description should be not compulsory

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#263]
![image](https://user-images.githubusercontent.com/58812881/87776882-1c858600-c846-11ea-8a5f-6e5ba518e76f.png)

https://www.fammeo.in/p/organization/create?n=test%20x&t=edu

https://www.fammeo.in/p/organization/create?n=test%20x&t=exp

**Comment by Avinash-ecb** [comment]
@mitulpanch please check this issue 
in create company api there is company description required

**Comment by mitulpanch** [comment]
yes its required. base company create api requires this.
