### ISSUE TITLE
Blog i button text pending 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#265]
![image](https://user-images.githubusercontent.com/58812881/87903367-728e3f80-ca79-11ea-8995-3573c93e8552.png)

1) Meta tags provide information about the webpage in the HTML of the document. This information is called "metadata" and while it is not displayed on the page itself, it can be read by search engines and web crawlers.

 2) The meta description is a snippet of up to about 155 characters – a tag in HTML – which summarizes a page's content. Search engines show it in search results mostly when the searched-for phrase is within the description. 

3) Industries - Link your blog to specific industry so that it is easily accessible to users. Leave blank if it is not related to specific industry

4) software - Link your blog to specific software so that it is easily accessible to users. Leave blank if it is not related to specific software

5) Legal structure - Link your blog to specific legal structure so that it is easily accessible to users. Leave blank if it is not related to specific legal structure

6) Tags - besides specific industry, software, legal structure if you want to categories your blog to specific categories, kindly make use of tags 

7) software - Link your blog to specific software so that it is easily accessible to users. Leave blank if it is not related to specific software

8) Active post ka button : Publish and Draft aisa karwa do.  
text ki jaroorat nahi hai

9) private post : Turn this on to display blog to your subscribers only

10)author name  me bhi text ki jaroorat nahi hai
private post : Turn this on to display blog to your subscribers only

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/87926841-e93e3380-ca9f-11ea-85ef-05cd273ae94c.png)

**Comment by jayshah6777** [comment]
![Uploading image.png…]()
