### ISSUE TITLE
show mouse text 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#266]
![image](https://user-images.githubusercontent.com/58812881/87903740-5939c300-ca7a-11ea-87c1-9d2893c592b4.png)

member about 
Add Tags
Add Skills
Add Hobbies

company About
Add Industry

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/87918206-b9892e80-ca93-11ea-85e7-7f248aec7b44.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/88013161-581b9b00-cb39-11ea-9d4f-cbf7683d57e9.png)
