### ISSUE TITLE
UI issue 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#267]
![image](https://user-images.githubusercontent.com/58812881/87904193-6acf9a80-ca7b-11ea-9872-15ab882da63f.png)

https://www.fammeo.in/p/organization/search?new

https://www.fammeo.in/p/organization/search?edu

https://www.fammeo.in/p/organization/search?exp

https://www.fammeo.in/p/user/search?cid=LURiWktlNzVDa3FJWXpOaUdGeTRWQQ==

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/87937079-a1c0a300-cab1-11ea-803c-f51b2a91e062.png)

**Comment by jayshah6777** [comment]
![Uploading image.png…]()

**Comment by jayshah6777** [comment]
https://www.fammeo.in/p/organization/connect?id=M2FpUlNYd2VpMDJzOHB1YUR1dDJmdw==&t=edu

https://www.fammeo.in/p/organization/connect?id=V2dQQjdpQmlMMHE0VzlaTEpRVWFRQQ==&t=exp

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/88173788-cb5c0480-cc40-11ea-9227-06cb1669ee30.png)

**Comment by jayshah6777** [comment]
https://www.fammeo.in/p/organization/create?n=fammeo&t=exp

**Comment by Avinash-ecb** [comment]
issue fixed

**Comment by Avinash-ecb** [comment]
#229

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/88369050-d2a02100-cdac-11ea-9472-037bf0a6a996.png)
