### ISSUE TITLE
UI issue on dashboard 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#270]
![image](https://user-images.githubusercontent.com/58812881/88015428-c44ccd80-cb3e-11ea-98b2-bf96bdb6cee2.png)

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/88015567-20175680-cb3f-11ea-902b-bcac7cdb0c94.png)

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/88020833-0596aa80-cb4a-11ea-95c0-cbf27083c6df.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/88136516-093c3700-cc07-11ea-99a4-b93841083b64.png)
