### ISSUE TITLE
Setting Save botton provide in down side

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#280]
![image](https://user-images.githubusercontent.com/58812881/88380291-ec982e80-cdc1-11ea-98e0-6c8abe336a47.png)

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/88387905-19a00d80-cdd1-11ea-874f-adbf785bc650.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/88448838-63cfd000-ce5f-11ea-8b84-44d30c85de18.png)
