### ISSUE TITLE
alumni show in team member otherwise create alumni tab in team

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#282]
1) jo job chhodke gaya ho wo b team me dikhne chahiye

**Comment by Avinash-ecb** [comment]
issue fixed 
![image](https://user-images.githubusercontent.com/46588125/88518647-71778800-d00e-11ea-82ac-dbd86faf9eb5.png)

**Comment by jayshah6777** [comment]
![Uploading image.png…]()
