### ISSUE TITLE
when user add address and try to save then show error 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#283]
![image](https://user-images.githubusercontent.com/58812881/88454028-f1281a00-ce89-11ea-8a2a-c474bb671f0c.png)

**Comment by Avinash-ecb** [comment]
@mitulpanch  please allow null Lat and Lang field to useraddress

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/88625463-63853e00-d0c6-11ea-88cb-87d8e008fb26.png)

**Comment by Avinash-ecb** [comment]
issue fixed
![image](https://user-images.githubusercontent.com/46588125/88755660-46607600-d17f-11ea-8ecc-534b3f004565.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/88882313-4b8cf600-d24f-11ea-8384-0bc249cd1859.png)
