### ISSUE TITLE
Remove "es" from popup massage

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#285]
![image](https://user-images.githubusercontent.com/58812881/88885718-a70eb200-d256-11ea-9226-2f7cc1d29433.png)

1) remove "es" from popup massage on about pagr of comapny or user
2) change poup massage When user remove somethjing and save print  "address remove sucessfully"
3) When user add somenthing print massage "address added sucessfully"

**Comment by Avinash-ecb** [comment]
issue fixed

**Comment by harshitaexpcon** [comment]
![image](https://user-images.githubusercontent.com/66782635/89291533-55ac5b80-d678-11ea-98db-368a8a9fb4e8.png)
