### ISSUE TITLE
show save & cancel button show in down 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#288]
![image](https://user-images.githubusercontent.com/58812881/88910294-e995b600-d279-11ea-8f34-177ce559bc88.png)

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/89017713-5f605700-d338-11ea-8790-9547fbf69bb5.png)

**Comment by jayshah6777** [comment]
![Uploading image.png…]()
