### ISSUE TITLE
we should provide auto load conversation list

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#289]
![image](https://user-images.githubusercontent.com/58812881/88910799-9cfeaa80-d27a-11ea-9d52-e2427133512f.png)

**Comment by dharmendraecb** [comment]
Auto scroll not possible

**Comment by ajayrajecb** [comment]
> Auto scroll not possible

ask mitul sir about this. ho jayega to acchi bat hai.
