### ISSUE TITLE
Theme issue in browser 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#29]
![image](https://user-images.githubusercontent.com/58812881/82782754-ba7a5700-9e7a-11ea-8c77-cdea92280334.png)

![image](https://user-images.githubusercontent.com/58812881/82783595-6b352600-9e7c-11ea-83da-2f722b7f06de.png)

  when i save dark theme in firefox after fammeo login in chrome That time open with Light teme

**Comment by dharmendraecb** [comment]
browser me save hota he theme ha

**Comment by jayshah6777** [comment]
to iska koi or solution nahi hein ?

**Comment by jayshah6777** [comment]
no slution
