### ISSUE TITLE
ui issue on team page

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#290]
![image](https://user-images.githubusercontent.com/58812881/88918783-ab9f8e80-d287-11ea-9c97-2adf2e7036a2.png)

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/89016759-e3194400-d336-11ea-9637-1c63ce4e0097.png)

**Comment by jayshah6777** [comment]
![Uploading image.png…]()
