### ISSUE TITLE
ui issue in create blog

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#291]
![image](https://user-images.githubusercontent.com/58812881/89010782-e1e31980-d32c-11ea-8fdf-96554b958e76.png)

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/89016120-cc262200-d335-11ea-8f1a-54973cd90392.png)

**Comment by jayshah6777** [comment]
![Uploading image.png…]()
