### ISSUE TITLE
UI issue in my blog 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#292]
![image](https://user-images.githubusercontent.com/58812881/89025670-e5829a80-d344-11ea-8248-d07f567c3217.png)

https://www.fammeo.in/p/member/jayshah/blog

**Comment by Avinash-ecb** [comment]
issue fixed
![image](https://user-images.githubusercontent.com/46588125/89100640-53e35d80-d416-11ea-867a-f4739c695926.png)

**Comment by jayshah6777** [comment]
https://github.com/Fammeo/Fammeo/issues/293
