### ISSUE TITLE
some times missing edit & delete blog button 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#293]
![image](https://user-images.githubusercontent.com/58812881/89026057-9f7a0680-d345-11ea-9627-a43cec5adf73.png)

**Comment by Avinash-ecb** [comment]
issue fixed
![image](https://user-images.githubusercontent.com/46588125/89100652-65c50080-d416-11ea-884e-7e343e542e94.png)

**Comment by jayshah6777** [comment]
![Uploading image.png…]()
