### ISSUE TITLE
ui issue create blog dropdown 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#298]
![image](https://user-images.githubusercontent.com/58812881/89615508-650fec80-d8a4-11ea-89b6-2bb8cd50a320.png)

**Comment by Avinash-ecb** [comment]
issue fixed
![image](https://user-images.githubusercontent.com/46588125/89706405-eb9afb80-d982-11ea-87f0-a601e36d41d5.png)
