### ISSUE TITLE
thumb image upload backgroud 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#299]
![image](https://user-images.githubusercontent.com/58812881/89615744-d5b70900-d8a4-11ea-9dcc-7f409d9e3888.png)

**Comment by Avinash-ecb** [comment]
issue fixed
![image](https://user-images.githubusercontent.com/46588125/89706418-22711180-d983-11ea-8509-a5a87ed1b0a9.png)
