### ISSUE TITLE
blog uploaded by company they are show on blog page

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#301]
![image](https://user-images.githubusercontent.com/58812881/89616551-36931100-d8a6-11ea-8bac-b77652b3dd35.png)

https://www.fammeo.in/p/blog

1) now show only member blog 
2)  should be show blog which is uploaded by company

**Comment by Avinash-ecb** [comment]
@mitulpanch please change in api according to this

**Comment by Avinash-ecb** [comment]
Issue solved

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/89856921-449fa500-dbb8-11ea-8efe-10bda323b29d.png)
