### ISSUE TITLE
ui isuue blog dropdown 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#304]
![image](https://user-images.githubusercontent.com/58812881/90010325-4a32e300-dcbd-11ea-8e2f-d955a994cc27.png)

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/90116438-1dd99e00-dd73-11ea-9893-58c5fc7535cf.png)
