### ISSUE TITLE
delete blog change notification(message)

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#307]
![image](https://user-images.githubusercontent.com/58812881/90242841-5ea4e600-de4b-11ea-977a-fbb7ddddebdb.png)

blog deleted successfully

**Comment by Avinash-ecb** [comment]
issue solved
![image](https://user-images.githubusercontent.com/46588125/90357445-9b055b80-e070-11ea-9927-1073f82c41b3.png)
