### ISSUE TITLE
city,state me gap rakho

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#31]
![Screenshot 2020-05-25 at 6 32 19 PM](https://user-images.githubusercontent.com/41849556/82815180-46f63b00-9eb6-11ea-90ae-e891d36109a6.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/83095465-03bbe800-a0c1-11ea-99e2-e4ec4f05ce17.png)
