### ISSUE TITLE
provide finish or next button

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#312]
![image](https://user-images.githubusercontent.com/58812881/90878396-15144800-e3c3-11ea-8fe4-5489eef2451f.png)

**Comment by Avinash-ecb** [comment]
issue solved

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/91124438-d7facf00-e6bc-11ea-8ee5-d82085de9ed8.png)
