### ISSUE TITLE
don't save Service Description by user 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#313]
![image](https://user-images.githubusercontent.com/58812881/91035022-8f430780-e623-11ea-8b03-aaf9e01bc17d.png)

https://www.fammeo.in/p/org/pranavsales/service/website?cid=-DbZKe75CkqIYzNiGFy4VA&id=BIKSxIEamUyO4Lny5cBX7A&t=new

**Comment by Avinash-ecb** [comment]
Issue fixed
