### ISSUE TITLE
save button show multiple time 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#314]
![image](https://user-images.githubusercontent.com/58812881/91035177-d204df80-e623-11ea-92f4-c477e5bed0f8.png)

https://www.fammeo.in/p/org/pranavsales/service/website?cid=-DbZKe75CkqIYzNiGFy4VA&id=BIKSxIEamUyO4Lny5cBX7A&t=new

**Comment by Avinash-ecb** [comment]
issue fixed
