### ISSUE TITLE
ui issue 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#315]
![image](https://user-images.githubusercontent.com/58812881/91036250-a33b3900-e624-11ea-89a3-8cd6f3caf62a.png)

**Comment by Avinash-ecb** [comment]
issue fixed

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/91684446-2e608580-eb75-11ea-8ce0-be438daefde7.png)
