### ISSUE TITLE
 open all file type in file upload

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#318]
![image](https://user-images.githubusercontent.com/58812881/91684640-ab8bfa80-eb75-11ea-893a-ae75efa372e0.png)

**Comment by mitulpanch** [comment]
@Avinash-ecb JPG, PNG, GIF on karo

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/106843334-cdad1a00-66cb-11eb-9b1f-b171d603b7a5.png)
issue fixed

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/106844288-1fef3a80-66ce-11eb-9889-9d87a33af693.png)

only opening image supported files
