### ISSUE TITLE
Change design member profile and organization profile

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/Fammeo#321]
In organization team page will not changed as discussed with @mitulpanch  sir 
![image](https://user-images.githubusercontent.com/46588125/97156128-4121c000-179c-11eb-8b02-8fe476ce228d.png)

**Comment by mitulpanch** [comment]
ye finish kardo pehle, jo bola tha @vinpahilwani sir ne

**Comment by Avinash-ecb** [comment]
This design is same in member profile all page and organisation profile all page so mitul sir suggest this will not changed
