### ISSUE TITLE
Send Button Is not Working

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#326]
https://mahesh-vadodara.fammeo.in/contactus

![contact us - send - button](https://user-images.githubusercontent.com/77724114/105317971-ef48d480-5be8-11eb-9edc-7aff90491414.png)
 
After Click on send button it does not clear any thing in kabru Theme any send message does not appear.

**Comment by Avinash-ecb** [comment]
@dharmendraecb this is server side error solve this

**Comment by Harsheasy** [comment]
![2021-02-15_11-03-59](https://user-images.githubusercontent.com/77724114/107909151-9d903180-6f7d-11eb-84fa-0b6d970a5e1d.png)
