### ISSUE TITLE
Facts Number does not Appear

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#327]
https://mahesh-vadodara.fammeo.in/index

![2021-01-21_13-07-39](https://user-images.githubusercontent.com/77724114/105318576-b6f5c600-5be9-11eb-859e-d881918a80ab.png)

I Give Value to client = 40 , project= 50  , team = 10 , service = 10 but it does not show out side in main website

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/105444848-a2bad300-5c94-11eb-8efa-4342ddf85777.png)
Now it is working
