### ISSUE TITLE
Sliding Image and Text does not change

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#328]
https://mahesh-vadodara.fammeo.in/Edit?page=index

![image](https://user-images.githubusercontent.com/77724114/105324713-c2e58600-5bf1-11eb-96f5-0600392847a5.png)

I upload images but it gives me an error message and after changing the text it does not appear in the sliding image. It happened in all the theme.

**Comment by Avinash-ecb** [comment]
@dharmendraecb please check this issue its working on easycloud website and not working in fammeo website
