### ISSUE TITLE
Redirect Issue in website mahesh-vadodara.fammeo.in

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#330]
https://mahesh-vadodara.fammeo.in/

Sometimes i can not redirect myself to another page, it does not happen all the time.

**Comment by dharmendraecb** [comment]
check again

**Comment by Harsheasy** [comment]
https://user-images.githubusercontent.com/77724114/105468543-196bc680-5cbd-11eb-9634-3ae2e639b84b.mp4
