### ISSUE TITLE
Design Issue In Jongsong Peak theme in logo

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#331]
![2021-01-21_14-35-35](https://user-images.githubusercontent.com/77724114/105328633-41442700-5bf6-11eb-8ac7-5e98a21f039d.png)
in jongsong peak theme, it automatically resizes the logo, set the size of the logo in the jongsong peak theme

**Comment by Avinash-ecb** [comment]
@Harsheasy If logo image size is big then it will create issue in header

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/105473406-183d9800-5cc3-11eb-8897-52cdc006fc93.png)
logo max height increase
