### ISSUE TITLE
Nanda Devi Theme Text can not change

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#332]
https://mahesh-vadodara.fammeo.in/

![image](https://user-images.githubusercontent.com/77724114/105330748-a9940800-5bf8-11eb-8f8e-093a33fb2b32.png)

Can not change the text in the appeared box, the button text change but upper text does not change

**Comment by Avinash-ecb** [comment]
@dharmendraecb please check this issue
