### ISSUE TITLE
Skill Text can not be change in Nanda Devi Theme 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#334]
https://mahesh-vadodara.fammeo.in/
![2021-01-21_15-54-12](https://user-images.githubusercontent.com/77724114/105338493-a2252c80-5c01-11eb-8294-df0ecb6d4f79.png)

I can not change skill Description in nanda devi theme

**Comment by mitulpanch** [comment]
@Harsheasy live tag ayega fir recheck karna he
