### ISSUE TITLE
Service image does not appear in Kangchenjunga Theme

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#335]
https://mahesh-vadodara.fammeo.in/index

![2021-01-22_12-21-12](https://user-images.githubusercontent.com/77724114/105457253-81fe7780-5cac-11eb-9296-8042ca7f76f1.png)

On Index page it should show images of service

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/105477538-001c4780-5cc8-11eb-8926-1fdb67556cf8.png)
Issue solved

**Comment by Harsheasy** [comment]
Yes service image appears but the image and text does do not come in a proper format

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/105571874-7cbb2e80-5d79-11eb-8014-53315da0edb5.png)
issue solved
