### ISSUE TITLE
Can not see about text in footer 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#337]
https://mahesh-vadodara.fammeo.in/index
![2021-01-22_15-43-11](https://user-images.githubusercontent.com/77724114/105478575-59d14180-5cc9-11eb-8e46-68dcea9ac121.png)

In some theme Footer display about the text but the user can not see that properly because of font color is back, make by default color for footer according to theme

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/105573965-379df900-5d87-11eb-8133-de978c1239e7.png)
issue fixed
