### ISSUE TITLE
Font color is not visible 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#339]
https://mahesh-vadodara.fammeo.in/aboutus
![2021-01-23_11-45-47](https://user-images.githubusercontent.com/77724114/105570699-28ac4c00-5d71-11eb-9e0f-add241d78f27.png)
In kanchenjunga theme font color is not visible it too light change theme color according to page and theme , it happened in whole theme not in a single page

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/105946737-d7140200-608d-11eb-903a-cbe36c571414.png)
issue solved
