### ISSUE TITLE
Need To Contact us Field Datatype Changes

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#348]
![2021-01-27_10-54-23](https://user-images.githubusercontent.com/77724114/105946903-1b9f9d80-608e-11eb-8858-053db5679532.png)

Phone No should be accept only numeric value

Email Id should be accept only email formet

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/106351587-4b0b1000-6303-11eb-8924-4d0ffaf939b7.png)
issue solved
