### ISSUE TITLE
Kabru Testimonial filed blank after updating

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#350]
![2021-01-27_14-44-17](https://user-images.githubusercontent.com/77724114/105969825-aee8cb00-60ae-11eb-99b7-6b337236cdc4.png)

I update testimonial section in indian ocean theme but in kabru theme it does not update properly

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/105971239-51557e00-60b0-11eb-9f12-9527f2d9a565.png)
issue fixed
