### ISSUE TITLE
Description does not show in website 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#355]
![image](https://user-images.githubusercontent.com/77724114/106419939-a104c280-647f-11eb-8f65-c7c0befeab3b.png)

**After adding the service , i wrote discription but it does not shown in website**

**Comment by Avinash-ecb** [comment]
issue fixed

**Comment by Avinash-ecb** [comment]
@dharmendraecb please check issue it works in easycloud website but not working in fammeo website

**Comment by Avinash-ecb** [comment]
issue fixed
![image](https://user-images.githubusercontent.com/46588125/108302709-8a25d600-71ca-11eb-8e08-e7095bee4859.png)
![image](https://user-images.githubusercontent.com/46588125/108302729-9316a780-71ca-11eb-92db-c59527e026b3.png)
