### ISSUE TITLE
User can't accept or ignore request 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#36]
![2020-05-27_1224](https://user-images.githubusercontent.com/58812881/82987483-35777500-a015-11ea-883d-939823c105ab.png)

1) whenever click on accept button show message (invalid request)
2) Whenever user get request that time send show notification on dashboard

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/83104190-d7f72d00-a0d5-11ea-92c0-4be421ac9c36.png)

**Comment by dharmendraecb** [comment]
live samko ho ga usme ayega

**Comment by dharmendraecb** [comment]
wait
