### ISSUE TITLE
It Should Show file name, after uploaded ( IN CONTACT US Form)

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#363]
**When user upload file or image it should show file name or image name on the contact us form, so the user does not get confused for uploaded file or image **

https://user-images.githubusercontent.com/77724114/107180923-ce152000-69ff-11eb-8125-9879902209e4.mp4

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/107608019-c1433700-6c60-11eb-817a-9debc07a9778.png)
we can show how many files are uploaded because there are option for multiple file upload we can't show file name
