### ISSUE TITLE
Issue In Contact Us Page

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#364]
**If I have entered only one address then it should show only one time on the contact us page** 

**And if the email id and mobile number is similar then it should show only one on the contact us page** 

**If there no other details of the user only one address, one mobile number, and one email id then view more button should be disabled** 

### Only the Indian ocean theme work correctly 

![2021-02-08_11-31-12](https://user-images.githubusercontent.com/77724114/107181948-de2dff00-6a01-11eb-93d8-b1db62ac9497.png)

**Comment by Avinash-ecb** [comment]
issue fixed
![image](https://user-images.githubusercontent.com/46588125/107500521-4294be00-6bbc-11eb-8de4-5d4a30dfec47.png)
