### ISSUE TITLE
Footer About description issue

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#365]
### IN Kangchenjunga , Nanda Devi AND Jongsong Peak Theme 
 Footer about description should contain only a few words not whole about section.
![2021-02-08_11-42-56](https://user-images.githubusercontent.com/77724114/107183122-2ea65c00-6a04-11eb-9efa-b31a28a2e5e0.png)

**Comment by Avinash-ecb** [comment]
Theire is different text in index about footer about and about page description and in footer only accept string
