### ISSUE TITLE
Can not update testimonial image 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#366]
When i update the image of testimonial , it gives me error message and in a new testimonial also same thing happened, i uploaded png image 

![2021-02-08_12-08-47](https://user-images.githubusercontent.com/77724114/107184397-7f1eb900-6a06-11eb-9f6c-f7e30e3806ed.png)

**Comment by Avinash-ecb** [comment]
now this issue is not happening
