### ISSUE TITLE
Header Image should be change 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#371]
### every website header image should be changed, example about page title image should be change

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/107759824-dd250680-6d4e-11eb-8ff7-451c12b3f9f7.png)
issue solved

**Comment by Harsheasy** [comment]
can not change the image, new error message appear
![image](https://user-images.githubusercontent.com/77724114/108023906-8f0f4c00-7049-11eb-91ec-83d866136930.png)

**Comment by Harsheasy** [comment]
![image](https://user-images.githubusercontent.com/77724114/108167869-60ae7100-711c-11eb-8f9a-f0b377da03a9.png)

**Comment by Avinash-ecb** [comment]
It is done in all theme except indian-ocean theme
