### ISSUE TITLE
can not see next button

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#374]
### while adding service can not see the next button 

![2 service](https://user-images.githubusercontent.com/77724114/108027542-5cb51d00-7050-11eb-8256-d0d2abaf9fd4.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/108155843-95fb9480-7105-11eb-9782-b0d8a04e771b.png)
issue solved
