### ISSUE TITLE
Changes in design of the page 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#379]
### Only in mercury theme remove the label to show the current page 
![image](https://user-images.githubusercontent.com/77724114/108334193-b277f980-71f7-11eb-91fd-b20dd5755981.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/108594774-e98a0e80-73a1-11eb-9476-e6a9f6f5d1a3.png)

issue fixed

**Comment by Harsheasy** [comment]
all theme ?

**Comment by Avinash-ecb** [comment]
changes done in all theme except indian-ocean
