### ISSUE TITLE
Same phone number shouldn't Add multiple time

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#38]
![image](https://user-images.githubusercontent.com/58812881/83095710-9066a600-a0c1-11ea-9944-ad7692baf284.png)

**Comment by jayshah6777** [comment]
1) Whenever Add new phone no then show multiple time that number

**Comment by jayshah6777** [comment]
![2020-06-02_1438](https://user-images.githubusercontent.com/58812881/83502135-cbf8da00-a4de-11ea-98a1-b8134f9cd63a.png)

**Comment by mitulpanch** [comment]
is this Design issue OR Api issue.
@Avinash-ecb  clear this

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/83836053-0a291000-a710-11ea-8b0b-95a6a46c6f52.png)

**Comment by Avinash-ecb** [comment]
Phone number issue is fixed now
