### ISSUE TITLE
Design issue in Themes (Software experience)

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#381]
### In software experience, there are some issue in a different theme which I provide images for themes below

![image](https://user-images.githubusercontent.com/77724114/108465151-77cd9a00-72a7-11eb-8868-e4b766cd31ee.png)
![image](https://user-images.githubusercontent.com/77724114/108465160-7a2ff400-72a7-11eb-9f88-e4e395db0954.png)
![image](https://user-images.githubusercontent.com/77724114/108465169-7dc37b00-72a7-11eb-8ba2-9279118570ca.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/108502877-7c12ab00-72d9-11eb-8fd3-1e02010a58ce.png)
issue solved in all theme except indian-ocean

**Comment by mitulpanch** [comment]
256 * 256  image is fixed now, everything need to be adjust with that
