### ISSUE TITLE
Design issue in Themes (INDUSTRY EXPERIENCE)

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#382]
![image](https://user-images.githubusercontent.com/77724114/108466052-0d1d5e00-72a9-11eb-95db-995067ce3fec.png)
![image](https://user-images.githubusercontent.com/77724114/108466064-10b0e500-72a9-11eb-81ea-208ce33093ac.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/108502780-5685a180-72d9-11eb-8415-3970b212e30c.png)
Issue solved in all theme except indian ocean
