### ISSUE TITLE
All Image should be change in every theme

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#383]
### User can change all images in websites like the background of the contact form, testimonial, software experience, and all the images should be changed in every theme

**Comment by Avinash-ecb** [comment]
issue fixed in all theme except indian ocean

**Comment by mitulpanch** [comment]
Site speed isse drastic change hoga,

Default image sari Compressed, Tested, Approved from Google He

User ko kuch nai samjta isme se,

Then Complain ata he ki site slow he

So, As Developer We can not do anything agar har kuch user ko karna he
