### ISSUE TITLE
Service description does not appear on the website 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#388]
### In fammeo admin all page filled like document required, the package includes and an FAQ but did not show on the website
 ![image](https://user-images.githubusercontent.com/77724114/109102598-3c234c00-774f-11eb-9586-cf86e550d30a.png)

**Comment by mitulpanch** [comment]
This is major issue, will  take time

**Comment by mitulpanch** [comment]
Currentlt  working on other things

**Comment by mitulpanch** [comment]
this is done finally
