### ISSUE TITLE
Default image does not appear in industry experience 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#389]
### Old image appears in another company wait for around 1 day to update but it still does not appear in other company's industry experience 

![2021-02-24_17-03-24](https://user-images.githubusercontent.com/77724114/109104160-86a5c800-7751-11eb-9c38-a60ff0cf5290.png)

**Comment by Avinash-ecb** [comment]
It should change image in about page industry section admin famm then it will reflect to other organisation industry
