### ISSUE TITLE
Images does not appear in industry experience In FAMMEO ADMIN profile

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#392]
### When user add industry experience in the fammeo admin section it shows in the suggestion but it did not get photos of that experience it generates automate images means image with text
![2021-02-25_17-15-21](https://user-images.githubusercontent.com/77724114/109149354-73b0e900-778d-11eb-8af2-385019644ebe.png)

**Comment by mitulpanch** [comment]
Its working Correctly
