### ISSUE TITLE
design change in buttons 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#393]
![image](https://user-images.githubusercontent.com/77724114/109153882-83333080-7793-11eb-831f-214d45c42f81.png)
### Change all the button and make like below 
![image](https://user-images.githubusercontent.com/77724114/109153939-99d98780-7793-11eb-9058-a3763cd185f3.png)

**Comment by ajayrajecb** [comment]
solid green nhi chahiye, sabhi buttons me only border chahiye.

**Comment by Harsheasy** [comment]
### In Fammeo when user change any image like industry experience and software experience and more it should show suggestion of image like in industry experience 256*256 image should be there. 
![image](https://user-images.githubusercontent.com/77724114/109256828-d8ffeb00-781c-11eb-9e40-3818417441e9.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/109461236-df45cf80-7a87-11eb-84d3-562a6221ccd7.png)
design chagne

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/109643629-80ad4e00-7b7a-11eb-9d59-6344bdd33971.png)
