### ISSUE TITLE
changes in Website and fammeo pop-up for update image 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#395]
### In website, it should show a suggestion of the image everywhere where the image can change 
**IN ALL THEME EVERYWHERE**
![image](https://user-images.githubusercontent.com/77724114/109257155-8115b400-781d-11eb-910c-d1976eee7065.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/109908086-a5fca200-7cc9-11eb-8bd3-421464335e5a.png)
Done in fammeo

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/110080863-16cab980-7db1-11eb-9b5f-ecc5ce04e94e.png)
Done in website
