### ISSUE TITLE
alignment issue in Mercury and Karakoram 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#399]
### Alignment should be according to the theme
![image](https://user-images.githubusercontent.com/77724114/109277176-f9d83880-783c-11eb-8a8f-441762b332fb.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/109296686-c1455880-7856-11eb-9e80-5ae9773f607a.png)
issue fixed
