### ISSUE TITLE
issue in suggestion in fammeo

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#400]
### and label should change "Add Details" to "Accept Request"
![image](https://user-images.githubusercontent.com/77724114/109287882-2cd4f900-784a-11eb-9a68-9f05d08f6688.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/109386165-dd143180-791e-11eb-8d3e-2d0ae8da9cca.png)

![image](https://user-images.githubusercontent.com/46588125/109386176-f5844c00-791e-11eb-8bf5-6f5b6ce0d3e8.png)

![image](https://user-images.githubusercontent.com/46588125/109386185-fe751d80-791e-11eb-8b9e-61ca3c7e0189.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/109386594-a0960500-7921-11eb-9e96-cff009f4b00d.png)

**Comment by Avinash-ecb** [comment]
1 In other suggestion if data is null then showing suggestion
2 In friendrequest case show suggestion if data found

**Comment by mitulpanch** [comment]
there is no api -error
