### ISSUE TITLE
Fammeo->About-> Industry -> first latter should be capital

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#401]
![image](https://user-images.githubusercontent.com/77724114/109378330-a24ad300-78f7-11eb-8ea5-bc689df7caae.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/109450060-01cbee80-7a70-11eb-825a-2e1b1003e237.png)
issue fixed
