### ISSUE TITLE
Footer about description words limits

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#407]
### Show footer about description according to them and gives words limit to about in footer

![image](https://user-images.githubusercontent.com/77724114/109495501-5e9dc800-7ab5-11eb-804f-70399196afdd.png)

**Comment by Avinash-ecb** [comment]
![image](https://user-images.githubusercontent.com/46588125/109634124-e267bb00-7b6e-11eb-846c-dfa1bc764521.png)
