### ISSUE TITLE
In Service genral description character limit fammeo and easycloudbooks

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#408]
### In-Service general tab give words limit to "**280**" because in different theme character does not display in the website so reduce the charater

**Comment by mitulpanch** [comment]
Or kahi use hote he?

**Comment by Harsheasy** [comment]
@mitulpanch Yes sir, website k heading meh use hota he , and vahi description group meh dikhta he.

![Snag_56e7aa5](https://user-images.githubusercontent.com/77724114/109960998-6b1d5d00-7d0f-11eb-8b19-062059bd8709.png)

**Comment by mitulpanch** [comment]
then Limit reduce nahi karte, aage use ayega, and html ka length dhundna possible nai he
