### ISSUE TITLE
Text Changes in fammeo website general

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#421]
### As per new update need to change text in general tab 
![2021-03-31_10-34-34](https://user-images.githubusercontent.com/77724114/113093221-19cc9480-920d-11eb-94d9-50c1eaf33afb.png)

**Comment by Avinash-ecb** [comment]
![Screenshot_2021-03-31 Website Setting - Fammeo](https://user-images.githubusercontent.com/46588125/113095028-5fd72780-9210-11eb-961d-66587d87bb39.png)

issue fixed
