### ISSUE TITLE
Fammeo social link not working in website 

### ISSUE THREAD

**Issue by Harsheasy** [Fammeo/Fammeo#423]
![image](https://user-images.githubusercontent.com/77724114/113680344-5ea96d00-96de-11eb-8688-f34a020754e8.png)
![Screenshot (2)](https://user-images.githubusercontent.com/77724114/113680355-61a45d80-96de-11eb-999c-9ba696faf287.png)

**Comment by Avinash-ecb** [comment]
it is getting encoded link from server
