### ISSUE TITLE
User already updated photo but not showing on right hand top side

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#47]
![2020-06-01_1026](https://user-images.githubusercontent.com/58812881/83377245-a4c4de80-a3f2-11ea-8cf2-55d7bc93479d.png)

1) it's photo fatch from gmail profile photo

**Comment by mitulpanch** [comment]
relogin ke bad bhi solve nai hota?

**Comment by jayshah6777** [comment]
Nahi hota he
