### ISSUE TITLE
banner image corner curve nahi aa rahe

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#5]

**Comment by mitulpanch** [comment]
![Annotation 2020-05-23 183308](https://user-images.githubusercontent.com/5259926/82731370-e46d3580-9d23-11ea-812f-c3f9c8eb1e30.jpg)


Not Curved yet

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/82857052-7b590e00-9f2d-11ea-9343-b15f4fafecee.png)



Resolve
