### ISSUE TITLE
social link nahi hai toh nahi dikhna chahiye

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#53]
![Screenshot 2020-06-04 at 8 37 23 AM](https://user-images.githubusercontent.com/41849556/83710667-e1851580-a63e-11ea-9582-bf8c05a51c8d.png)

**Comment by Avinash-ecb** [comment]
this issue is fixed

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/84260021-f67a1100-ab36-11ea-9800-163a2ec28daa.png)
