### ISSUE TITLE
tweet pe aisa design nahi aana chahiye 

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#55]
aisa dikhao twitter account not linked with profile
![Screenshot 2020-06-04 at 8 42 41 AM](https://user-images.githubusercontent.com/41849556/83710912-78ea6880-a63f-11ea-8ef6-1de341320911.png)

**Comment by Avinash-ecb** [comment]
now displayed msg on own profile tweet page your tweeter account is not linked with your profile 
if other user can not see tweet menu if tweeter id is not saved in social links
