### ISSUE TITLE
pehla phone number display me office dikhta hai and edit mein blank

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#59]
![Screenshot 2020-06-05 at 9 20 40 AM](https://user-images.githubusercontent.com/41849556/83835338-2926a280-a70e-11ea-85d6-465836ed4e0e.png)

**Comment by vinpahilwani** [comment]
Office ka O kabhi chhota kabhi bada aisa kyu

**Comment by Avinash-ecb** [comment]
@vinpahilwani  sir ek bar select kar ke save kar do to problem phir nahi aayegi
