### ISSUE TITLE
user ko khud ka number and email toh dikhna chahiye

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#6]
![Screenshot 2020-05-23 at 5 48 40 AM](https://user-images.githubusercontent.com/41849556/82717318-11383300-9cb9-11ea-875b-8b83716ad018.png)

**Comment by vinpahilwani** [comment]
1. workspace ko change karke Personal Profile kar do
2. MyDashboard ko Change karke My Dashboard karo
3. My Dashboard and Personal Profile ke beech ki gap ko kam karo
4. Organisation ko My Organisations kardo
5. Personal profile and Organisations k beech me divider rakha hai usko nikaal do and

**Comment by mitulpanch** [comment]
organisation -> organization
Everywhere

**Comment by dharmendraecb** [comment]
okyy
