### ISSUE TITLE
Me apna tweet set kaise karoon

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#60]
![Screenshot 2020-06-05 at 9 24 55 AM](https://user-images.githubusercontent.com/41849556/83835484-86225880-a70e-11ea-9dee-f37437f104b8.png)

**Comment by vinpahilwani** [comment]
2. design issue aisa blank box kya kar raha hai tweets mein

**Comment by Avinash-ecb** [comment]
about menu me social section me twitter ka link add kar sakte ho

**Comment by Avinash-ecb** [comment]
Now I Showed msg Your tweeter account is not connect to your profile id there is no any tweeter account connection to member profile
