### ISSUE TITLE
maine in dono ko follow back kiya hai phir bhi button aisa aa raha hai.

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#61]
dusra jaise hi follow back karoon toh button nikal jaana chahiye 
![Screenshot 2020-06-05 at 9 31 33 AM](https://user-images.githubusercontent.com/41849556/83835835-7e16e880-a70f-11ea-86d5-4b7bea855033.png)

**Comment by vinpahilwani** [comment]
following and followers me dono me follow back aata hai

Unfollow button kahan hai

**Comment by dharmendraecb** [comment]
fixed ho gaya he ek bar re check karl lo
