### ISSUE TITLE
About - No Content Message

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/Fammeo#62]
![Annotation 2020-06-05 152627](https://user-images.githubusercontent.com/5259926/83863479-02ce2a80-a741-11ea-91c9-2108182aa1d0.jpg)

**Comment by mitulpanch** [comment]
![Annotation 2020-06-05 152627](https://user-images.githubusercontent.com/5259926/83863546-18dbeb00-a741-11ea-83e5-25b9e55eb264.jpg)

**Comment by Avinash-ecb** [comment]
this issues about and social section now show msg when there is no content
