### ISSUE TITLE
Phone number and Email not getting from database 

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/Fammeo#69]
1 Phone number  and email has already added in database 
2 in api HavePermission function get false value so it can not get email and phone number of him
![image](https://user-images.githubusercontent.com/46588125/83998674-bc660f00-a97e-11ea-9cff-09c14b6b2a0c.png)

**Comment by mitulpanch** [comment]
any context?

login pe / without login?
token bheja tha?

**Comment by Avinash-ecb** [comment]
login ke bad mere profile me
