### ISSUE TITLE
My exeperiance and education show on all member profile 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#72]
![image](https://user-images.githubusercontent.com/58812881/84005202-5ed7bf80-a98a-11ea-9952-a2a960ac24dc.png)

![image](https://user-images.githubusercontent.com/58812881/84005226-68612780-a98a-11ea-831d-57f5ad47ff5c.png)

1) every member able to edit and delete. as per my opinion only profile owner should be able to edit & delete experience and education

**Comment by Avinash-ecb** [comment]
this issue is now fixed but software experience and industry experience is remaining because api not changed
