### ISSUE TITLE
Phone no & email id save button missing in popup window 

### ISSUE THREAD

**Issue by jayshah6777** [Fammeo/Fammeo#73]
![image](https://user-images.githubusercontent.com/58812881/84005472-cbeb5500-a98a-11ea-9c4c-e05690ff065f.png)

**Comment by Avinash-ecb** [comment]
this issue is fixed now save button is availabe

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/84259826-a9963a80-ab36-11ea-8e8a-54934071df9a.png)
