### ISSUE TITLE
Center Align - Vinod PAhilwani

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/Fammeo#81]
![](https://lh3.googleusercontent.com/-74EuV7ti8NE/XuDVA4VXVHI/AAAAAAAAu2U/icOytJFqz00Xc8H5FVTxYst5ZGEtdcIIQCK8BGAsYHg/s0/2020-06-10.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/84862969-be705200-b091-11ea-9a3f-86d8c6bb242c.png)
