### ISSUE TITLE
mujhe email ka type toh change karne do bhale default email change mat karne do

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#9]
![Screenshot 2020-05-23 at 6 09 59 AM](https://user-images.githubusercontent.com/41849556/82717777-0c28b300-9cbc-11ea-9a71-4ada0c4086f5.png)

**Comment by vinpahilwani** [comment]
2. add new entry ko left side le lo and blank portion nikal do box ko chhota kardo popup me blank area kam aana chahiye

**Comment by jayshah6777** [comment]
Resolve
