### ISSUE TITLE
Changes design in my dashboard

### ISSUE THREAD

**Issue by Avinash-ecb** [Fammeo/Fammeo#91]

**Comment by jayshah6777** [comment]
![2020-06-12_0925](https://user-images.githubusercontent.com/58812881/84463361-289e8680-ac8f-11ea-8a7b-43a215b4b7d5.png)

**Comment by Avinash-ecb** [comment]
@jayshah6777 please discuss with @vinpahilwani and if any issue found then reply me

**Comment by vinpahilwani** [comment]
maine koi design change nahi bola hai. abhi jo hai achha hai
