### ISSUE TITLE
Cancel nai chal raha

### ISSUE THREAD

**Issue by mitulpanch** [Fammeo/Fammeo#92]
![Annotation 2020-06-11 164402](https://user-images.githubusercontent.com/5259926/84379029-c8fa9980-ac02-11ea-8b22-2ff590805f9c.jpg)

**Comment by jayshah6777** [comment]
when Click on Cancel button remove Title, Description & Youtube video link

**Comment by jayshah6777** [comment]
when click on cancel button that time close popup window

**Comment by Avinash-ecb** [comment]
Now all modal popup will close on cancel button in member profile page
