### ISSUE TITLE
photo and name center me aana chahiye

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#95]
![Screenshot 2020-06-12 at 6 48 56 AM](https://user-images.githubusercontent.com/41849556/84454673-e1a59680-ac78-11ea-83b8-0dcf5555803c.png)

**Comment by vinpahilwani** [comment]
![Screenshot 2020-06-12 at 7 00 05 AM](https://user-images.githubusercontent.com/41849556/84455239-6cd35c00-ac7a-11ea-861c-3f514e87a4e4.png)

yeh background pura nahi hoa chahiye. sirf purple border honi chahiye

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/84618275-54b84280-aeef-11ea-920f-f1d592bebff6.png)
