### ISSUE TITLE
Practice Manager 

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#97]
login menu k neeche ek option dena hai - Practice Manager. Uspe click karne pe woh companies dikhani hai jahan pe login person staff hai easycloudbooks me. 

details to show:
company name
subdomain ya main domian name 
Owner name

My Dashboard mein:
to start practice manager button hona chahiye

**Comment by mitulpanch** [comment]
too early to say anything,
but my dashboard pe comanies aa jayegi jaha woh ja sakta he

**Comment by mitulpanch** [comment]
my dashboard pe woh companies aati hai jahan woh admin hai
jahan woh staff hai and admin nahi hai
woh nahi aayegi

- Vinod Pahilwani

**Comment by mitulpanch** [comment]
ok
dusra page aa jayega jahan ecb companies dikhe login ke jagah

**Comment by vinpahilwani** [comment]
Staff invite practice manager mein jaise hota hai waise hota hai. staff fammeo pe profile banayega agar nahi hai toh. 

agar uska profile already hai toh usko invitation aana chahiye- practice manager are mein

**Comment by mitulpanch** [comment]
Email se hum invitation bhejte he,
so incoming user can create other profile/ or login with ither email,
which employer may not know,

jab login kare tab pata chalta he kon user ki bat ho rahi he

**Comment by mitulpanch** [comment]
hum direct user ko mail nai karte, jisse pata chale ke user ke kitne panding invitation he
