### ISSUE TITLE
maine abhi tak facebook and twitter nahi diya phir bhi icon dikh raha hai

### ISSUE THREAD

**Issue by vinpahilwani** [Fammeo/Fammeo#99]

**Comment by Avinash-ecb** [comment]
this issue is solved from my side 
![image](https://user-images.githubusercontent.com/46588125/84980169-f7223100-b14e-11ea-9311-68a6ca43a92b.png)

**Comment by jayshah6777** [comment]
![image](https://user-images.githubusercontent.com/58812881/84983297-0c4e8e00-b156-11ea-8329-a70d03ec472a.png)
